[mypy]
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main
python_version = 3.12
strict = false
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = false

[mypy.plugins.django-stubs]
django_settings_module = core.settings

[mypy-channels.*]
ignore_missing_imports = true

[mypy-channels_redis.*]
ignore_missing_imports = true

[mypy-daphne.*]
ignore_missing_imports = true